.TH "src/cparse/acl.h" 3 "Thu Feb 26 2015" "Version 0.1" "cParse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cparse/acl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cparse/defines\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcParseACL\fP * \fBcparse_acl_new\fP ()"
.br
.ti -1c
.RI "\fBcParseACL\fP * \fBcparse_acl_new_with_user\fP (\fBcParseObject\fP *user)"
.br
.ti -1c
.RI "\fBcParseACL\fP * \fBcparse_acl_copy\fP (\fBcParseACL\fP *other)"
.br
.ti -1c
.RI "void \fBcparse_set_default_acl\fP (\fBcParseACL\fP *acl, bool currentUserAccess)"
.br
.ti -1c
.RI "void \fBcparse_acl_free\fP (\fBcParseACL\fP *acl)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cParse from the source code\&.
