.TH "src/cparse/defines.h" 3 "Sat Aug 1 2015" "Version 0.1" "cParse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cparse/defines.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBBEGIN_DECL\fP"
.br
.ti -1c
.RI "#define \fBEND_DECL\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbool\fP"
.br
.ti -1c
.RI "typedef int \fBcParseNumber\fP"
.br
.ti -1c
.RI "typedef struct cparse_error \fBcParseError\fP"
.br
.ti -1c
.RI "typedef struct cparse_object \fBcParseObject\fP"
.br
.ti -1c
.RI "typedef struct cparse_object \fBcParseUser\fP"
.br
.ti -1c
.RI "typedef struct cparse_object \fBcParseRole\fP"
.br
.ti -1c
.RI "typedef struct cparse_query \fBcParseQuery\fP"
.br
.ti -1c
.RI "typedef struct cparse_query_builder \fBcParseQueryBuilder\fP"
.br
.ti -1c
.RI "typedef void(* \fBcParseObjectCallback\fP) (\fBcParseObject\fP *obj, \fBcParseError\fP *error, void *param)"
.br
.ti -1c
.RI "typedef struct json_object \fBcParseJson\fP"
.br
.ti -1c
.RI "typedef void(* \fBcParseListFreeFunk\fP) (void *)"
.br
.ti -1c
.RI "typedef struct cparse_list_node \fBcParseListNode\fP"
.br
.ti -1c
.RI "typedef struct cparse_list \fBcParseList\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcParseAccess\fP { \fBcParseAccessRead\fP, \fBcParseAccessWrite\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct cparse_error \fBcParseError\fP"
An error structure 
.SS "typedef struct json_object \fBcParseJson\fP"
a json structure 
.SS "typedef struct cparse_list \fBcParseList\fP"
a list of a type 
.SS "typedef void(* cParseListFreeFunk) (void *)"
frees a node in a list 
.SS "typedef struct cparse_list_node \fBcParseListNode\fP"
a node in a list 
.SS "typedef int \fBcParseNumber\fP"
a type representing an integral number 
.SS "typedef struct cparse_object \fBcParseObject\fP"
A parse object structure 
.SS "typedef void(* cParseObjectCallback) (\fBcParseObject\fP *obj, \fBcParseError\fP *error, void *param)"
An object callback function 
.SS "typedef struct cparse_query \fBcParseQuery\fP"
A parse query structure 
.SS "typedef struct cparse_object \fBcParseRole\fP"
A parse role structure 
.SS "typedef struct cparse_object \fBcParseUser\fP"
A parse user structure 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcParseAccess\fP"
types of access for an object 
.SH "Author"
.PP 
Generated automatically by Doxygen for cParse from the source code\&.
