.TH "src/cparse/types.h" 3 "Sat Aug 1 2015" "Version 0.1" "cParse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cparse/types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cparse/defines\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "BEGIN_DECL \fBcParseJson\fP * \fBcparse_pointer_from_object\fP (\fBcParseObject\fP *obj)"
.br
.ti -1c
.RI "bool \fBcparse_json_is_pointer\fP (\fBcParseJson\fP *json)"
.br
.ti -1c
.RI "bool \fBcparse_json_is_bytes\fP (\fBcParseJson\fP *json)"
.br
.ti -1c
.RI "bool \fBcparse_json_is_file\fP (\fBcParseJson\fP *json)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cParse from the source code\&.
