.TH "src/cparse/util.h" 3 "Thu Jul 23 2015" "Version 0.1" "cParse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cparse/util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include <cparse/defines\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "BEGIN_DECL int \fBcparse_str_empty\fP (const char *str)"
.br
.ti -1c
.RI "time_t \fBcparse_date_time\fP (const char *str)"
.br
.ti -1c
.RI "void \fBcparse_replace_str\fP (char **a, const char *b)"
.br
.ti -1c
.RI "int \fBcparse_str_prefix\fP (const char *a, const char *b)"
.br
.ti -1c
.RI "int \fBcparse_str_cmp\fP (const char *a, const char *b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cParse from the source code\&.
